// Copyright (c) 2023 Maxim [maxirmx] Samsonov (https://sw.consulting)
// All rights reserved.
// This file is a part of rucades

#include "rucades.h"

namespace rucades {
void define_constants(VALUE module) {
  rb_define_const(module,  "CADESCOM_STRING_TO_UCS2LE", INT2NUM(CADESCOM_STRING_TO_UCS2LE));
  rb_define_const(module,  "CADESCOM_BASE64_TO_BINARY", INT2NUM(CADESCOM_BASE64_TO_BINARY));
  rb_define_const(module,  "CADESCOM_MEMORY_STORE", INT2NUM(CADESCOM_MEMORY_STORE));
  rb_define_const(module,  "CADESCOM_LOCAL_MACHINE_STORE", INT2NUM(CADESCOM_LOCAL_MACHINE_STORE));
  rb_define_const(module,  "CADESCOM_CURRENT_USER_STORE", INT2NUM(CADESCOM_CURRENT_USER_STORE));
  rb_define_const(module,  "CADESCOM_CONTAINER_STORE", INT2NUM(CADESCOM_CONTAINER_STORE));
  rb_define_const(module,  "CADESCOM_XML_SIGNATURE_TYPE_ENVELOPED", INT2NUM(CADESCOM_XML_SIGNATURE_TYPE_ENVELOPED));
  rb_define_const(module,  "CADESCOM_XML_SIGNATURE_TYPE_ENVELOPING", INT2NUM(CADESCOM_XML_SIGNATURE_TYPE_ENVELOPING));
  rb_define_const(module,  "CADESCOM_XML_SIGNATURE_TYPE_TEMPLATE", INT2NUM(CADESCOM_XML_SIGNATURE_TYPE_TEMPLATE));
  rb_define_const(module,  "CADESCOM_CADES_DEFAULT", INT2NUM(CADESCOM_CADES_DEFAULT));
  rb_define_const(module,  "CADESCOM_CADES_BES", INT2NUM(CADESCOM_CADES_BES));
  rb_define_const(module,  "CADESCOM_CADES_T", INT2NUM(CADESCOM_CADES_T));
  rb_define_const(module,  "CADESCOM_CADES_X_LONG_TYPE_1", INT2NUM(CADESCOM_CADES_X_LONG_TYPE_1));
  rb_define_const(module,  "CADESCOM_PKCS7_TYPE", INT2NUM(CADESCOM_PKCS7_TYPE));
  rb_define_const(module,  "CADESCOM_ENCODE_BASE64", INT2NUM(0));
  rb_define_const(module,  "CADESCOM_ENCODE_BINARY", INT2NUM(1));
  rb_define_const(module,  "CADESCOM_XADES_DEFAULT", INT2NUM(0x00000010));
  rb_define_const(module,  "CADESCOM_XADES_BES", INT2NUM(0x00000020));
  rb_define_const(module,  "CADESCOM_XADES_T", INT2NUM(0x00000050));
  rb_define_const(module,  "CADESCOM_XADES_X_LONG_TYPE_1", INT2NUM(0x000005d0));
  rb_define_const(module,  "CADESCOM_XADES_A", INT2NUM(0x000007d0));
  rb_define_const(module,  "CADESCOM_XMLDSIG_TYPE", INT2NUM(0));
  rb_define_const(module,  "CAPICOM_LOCAL_MACHINE_STORE", INT2NUM(1));
  rb_define_const(module,  "CAPICOM_CURRENT_USER_STORE", INT2NUM(2));
  rb_define_const(module,  "CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED", INT2NUM(2));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_INCLUDE_WHOLE_CHAIN", INT2NUM(1));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_INCLUDE_END_ENTITY_ONLY", INT2NUM(2));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_INCLUDE_CHAIN_EXCEPT_ROOT", INT2NUM(0));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_SHA1_HASH", INT2NUM(CAPICOM_CERTIFICATE_FIND_SHA1_HASH));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_SUBJECT_NAME", INT2NUM(CAPICOM_CERTIFICATE_FIND_SUBJECT_NAME));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_ISSUER_NAME", INT2NUM(CAPICOM_CERTIFICATE_FIND_ISSUER_NAME));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_ROOT_NAME", INT2NUM(CAPICOM_CERTIFICATE_FIND_ROOT_NAME));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_TEMPLATE_NAME", INT2NUM(CAPICOM_CERTIFICATE_FIND_TEMPLATE_NAME));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_EXTENSION", INT2NUM(CAPICOM_CERTIFICATE_FIND_EXTENSION));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_EXTENDED_PROPERTY", INT2NUM(CAPICOM_CERTIFICATE_FIND_EXTENDED_PROPERTY));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_APPLICATION_POLICY", INT2NUM(CAPICOM_CERTIFICATE_FIND_APPLICATION_POLICY));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_CERTIFICATE_POLICY", INT2NUM(CAPICOM_CERTIFICATE_FIND_CERTIFICATE_POLICY));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_TIME_VALID", INT2NUM(CAPICOM_CERTIFICATE_FIND_TIME_VALID));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_TIME_NOT_YET_VALID", INT2NUM(CAPICOM_CERTIFICATE_FIND_TIME_NOT_YET_VALID));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_TIME_EXPIRED", INT2NUM(CAPICOM_CERTIFICATE_FIND_TIME_EXPIRED));
  rb_define_const(module,  "CAPICOM_CERTIFICATE_FIND_KEY_USAGE", INT2NUM(CAPICOM_CERTIFICATE_FIND_KEY_USAGE));
  rb_define_const(module,  "CAPICOM_PROPID_ENHKEY_USAGE", INT2NUM(CAPICOM_PROPID_ENHKEY_USAGE));
  // ... pki/cppcades/cppcades.h:enum _CAPICOM_CERT_INFO_TYPE
  rb_define_const(module,  "CAPICOM_CERT_INFO_SUBJECT_SIMPLE_NAME", INT2NUM(CAPICOM_CERT_INFO_SUBJECT_SIMPLE_NAME));
  rb_define_const(module,  "CAPICOM_CERT_INFO_ISSUER_SIMPLE_NAME", INT2NUM(CAPICOM_CERT_INFO_ISSUER_SIMPLE_NAME));
  rb_define_const(module,  "CAPICOM_CERT_INFO_SUBJECT_EMAIL_NAME", INT2NUM(CAPICOM_CERT_INFO_SUBJECT_EMAIL_NAME));
  rb_define_const(module,  "CAPICOM_CERT_INFO_ISSUER_EMAIL_NAME", INT2NUM(CAPICOM_CERT_INFO_ISSUER_EMAIL_NAME));
  rb_define_const(module,  "CAPICOM_CERT_INFO_SUBJECT_UPN", INT2NUM(CAPICOM_CERT_INFO_SUBJECT_UPN));
  rb_define_const(module,  "CAPICOM_CERT_INFO_ISSUER_UPN", INT2NUM(CAPICOM_CERT_INFO_ISSUER_UPN));
  rb_define_const(module,  "CAPICOM_CERT_INFO_SUBJECT_DNS_NAME", INT2NUM(CAPICOM_CERT_INFO_SUBJECT_DNS_NAME));
  rb_define_const(module,  "CAPICOM_CERT_INFO_ISSUER_DNS_NAME", INT2NUM(CAPICOM_CERT_INFO_ISSUER_DNS_NAME));
// ... pki/cppcades/cppcades.h: enum _CAPICOM_ENCODING_TYPE
  rb_define_const(module,  "CAPICOM_ENCODE_BASE64", INT2NUM(CAPICOM_ENCODE_BASE64));
  rb_define_const(module,  "CAPICOM_ENCODE_BINARY", INT2NUM(CAPICOM_ENCODE_BINARY));
  rb_define_const(module,  "CAPICOM_ENCODE_ANY", LONG2NUM(CAPICOM_ENCODE_ANY));
  // ... pki/cppcades/cppcades.h: enum_CAPICOM_EKU
  rb_define_const(module,  "CAPICOM_EKU_OTHER", INT2NUM(CAPICOM_EKU_OTHER));
  rb_define_const(module,  "CAPICOM_EKU_SERVER_AUTH", INT2NUM(CAPICOM_EKU_SERVER_AUTH));
  rb_define_const(module,  "CAPICOM_EKU_CLIENT_AUTH", INT2NUM(CAPICOM_EKU_CLIENT_AUTH));
  rb_define_const(module,  "CAPICOM_EKU_CODE_SIGNING", INT2NUM(CAPICOM_EKU_CODE_SIGNING));
  rb_define_const(module,  "CAPICOM_EKU_EMAIL_PROTECTION", INT2NUM(CAPICOM_EKU_EMAIL_PROTECTION));
  rb_define_const(module,  "CAPICOM_EKU_SMARTCARD_LOGON", INT2NUM(CAPICOM_EKU_SMARTCARD_LOGON));
  // ... pki/cppcades/cppcades.h: enum _CAPICOM_ATTRIBUTE
  rb_define_const(module,  "CAPICOM_AUTHENTICATED_ATTRIBUTE_SIGNING_TIME", INT2NUM(CAPICOM_AUTHENTICATED_ATTRIBUTE_SIGNING_TIME));
  rb_define_const(module,  "CAPICOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_NAME", INT2NUM(CAPICOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_NAME));
  rb_define_const(module,  "CAPICOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_DESCRIPTION", INT2NUM(CAPICOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_DESCRIPTION));
  // ... pki/cppcades/cppcades.h: enum _CADESCOM_ATTRIBUTE
  rb_define_const(module,  "CADESCOM_AUTHENTICATED_ATTRIBUTE_SIGNING_TIME", INT2NUM(CADESCOM_AUTHENTICATED_ATTRIBUTE_SIGNING_TIME));
  rb_define_const(module,  "CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_NAME", INT2NUM(CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_NAME));
  rb_define_const(module,  "CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_DESCRIPTION", INT2NUM(CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_DESCRIPTION));
  rb_define_const(module,  "CADESCOM_AUTHENTICATED_ATTRIBUTE_MACHINE_INFO", INT2NUM(CADESCOM_AUTHENTICATED_ATTRIBUTE_MACHINE_INFO));
  rb_define_const(module,  "CADESCOM_ATTRIBUTE_OTHER", INT2NUM(CADESCOM_ATTRIBUTE_OTHER));
  //..
  rb_define_const(module,  "CADESCOM_DISPLAY_DATA_NONE", INT2NUM(0));
  rb_define_const(module,  "CADESCOM_DISPLAY_DATA_CONTENT", INT2NUM(1));
  rb_define_const(module,  "CADESCOM_DISPLAY_DATA_ATTRIBUTE", INT2NUM(2));
  // ... pki/cppcades/cppcades.h: enum _CADESCOM_ENCRYPTION_ALGORITHM
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_RC2", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_RC2));
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_RC4", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_RC4));
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_DES", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_DES));
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_3DES", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_3DES));
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_AES", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_AES));
  rb_define_const(module,  "CADESCOM_ENCRYPTION_ALGORITHM_GOST_28147_89", INT2NUM(CADESCOM_ENCRYPTION_ALGORITHM_GOST_28147_89));
  // ... pki/cppcades/cppcades.h: enum _CAPICOM_HASH_ALGORITHM
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_SHA1", INT2NUM(CAPICOM_HASH_ALGORITHM_SHA1));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_MD2", INT2NUM(CAPICOM_HASH_ALGORITHM_MD2));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_MD4", INT2NUM(CAPICOM_HASH_ALGORITHM_MD4));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_MD5", INT2NUM(CAPICOM_HASH_ALGORITHM_MD5));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_SHA_256", INT2NUM(CAPICOM_HASH_ALGORITHM_SHA_256));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_SHA_384", INT2NUM(CAPICOM_HASH_ALGORITHM_SHA_384));
  rb_define_const(module,  "CAPICOM_HASH_ALGORITHM_SHA_512", INT2NUM(CAPICOM_HASH_ALGORITHM_SHA_512));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411_HMAC", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411_HMAC));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256_HMAC", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256_HMAC));
  rb_define_const(module,  "CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512_HMAC", INT2NUM(CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512_HMAC));
  // ... enum _CAPICOM_ENCRYPTION_KEY_LENGTH
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_MAXIMUM", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_MAXIMUM));
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_40_BITS", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_40_BITS));
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_56_BITS", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_56_BITS));
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_128_BITS", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_128_BITS));
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_192_BITS", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_192_BITS));
  rb_define_const(module,  "CAPICOM_ENCRYPTION_KEY_LENGTH_256_BITS", INT2NUM(CAPICOM_ENCRYPTION_KEY_LENGTH_256_BITS));
  // ... enum _CAPICOM_OID
  rb_define_const(module,  "CAPICOM_OID_OTHER", INT2NUM(CAPICOM_OID_OTHER));
  rb_define_const(module,  "CAPICOM_OID_AUTHORITY_KEY_IDENTIFIER_EXTENSION", INT2NUM(CAPICOM_OID_AUTHORITY_KEY_IDENTIFIER_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_KEY_ATTRIBUTES_EXTENSION", INT2NUM(CAPICOM_OID_KEY_ATTRIBUTES_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_CERT_POLICIES_95_EXTENSION", INT2NUM(CAPICOM_OID_CERT_POLICIES_95_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_KEY_USAGE_RESTRICTION_EXTENSION", INT2NUM(CAPICOM_OID_KEY_USAGE_RESTRICTION_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_LEGACY_POLICY_MAPPINGS_EXTENSION", INT2NUM(CAPICOM_OID_LEGACY_POLICY_MAPPINGS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_SUBJECT_ALT_NAME_EXTENSION", INT2NUM(CAPICOM_OID_SUBJECT_ALT_NAME_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_ISSUER_ALT_NAME_EXTENSION", INT2NUM(CAPICOM_OID_ISSUER_ALT_NAME_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_BASIC_CONSTRAINTS_EXTENSION", INT2NUM(CAPICOM_OID_BASIC_CONSTRAINTS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_SUBJECT_KEY_IDENTIFIER_EXTENSION", INT2NUM(CAPICOM_OID_SUBJECT_KEY_IDENTIFIER_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_KEY_USAGE_EXTENSION", INT2NUM(CAPICOM_OID_KEY_USAGE_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_PRIVATEKEY_USAGE_PERIOD_EXTENSION", INT2NUM(CAPICOM_OID_PRIVATEKEY_USAGE_PERIOD_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_SUBJECT_ALT_NAME2_EXTENSION", INT2NUM(CAPICOM_OID_SUBJECT_ALT_NAME2_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_ISSUER_ALT_NAME2_EXTENSION", INT2NUM(CAPICOM_OID_ISSUER_ALT_NAME2_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_BASIC_CONSTRAINTS2_EXTENSION", INT2NUM(CAPICOM_OID_BASIC_CONSTRAINTS2_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_NAME_CONSTRAINTS_EXTENSION", INT2NUM(CAPICOM_OID_NAME_CONSTRAINTS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_CRL_DIST_POINTS_EXTENSION", INT2NUM(CAPICOM_OID_CRL_DIST_POINTS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_CERT_POLICIES_EXTENSION", INT2NUM(CAPICOM_OID_CERT_POLICIES_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_POLICY_MAPPINGS_EXTENSION", INT2NUM(CAPICOM_OID_POLICY_MAPPINGS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_AUTHORITY_KEY_IDENTIFIER2_EXTENSION", INT2NUM(CAPICOM_OID_AUTHORITY_KEY_IDENTIFIER2_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_POLICY_CONSTRAINTS_EXTENSION", INT2NUM(CAPICOM_OID_POLICY_CONSTRAINTS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_ENHANCED_KEY_USAGE_EXTENSION", INT2NUM(CAPICOM_OID_ENHANCED_KEY_USAGE_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_CERTIFICATE_TEMPLATE_EXTENSION", INT2NUM(CAPICOM_OID_CERTIFICATE_TEMPLATE_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_APPLICATION_CERT_POLICIES_EXTENSION", INT2NUM(CAPICOM_OID_APPLICATION_CERT_POLICIES_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_APPLICATION_POLICY_MAPPINGS_EXTENSION", INT2NUM(CAPICOM_OID_APPLICATION_POLICY_MAPPINGS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_APPLICATION_POLICY_CONSTRAINTS_EXTENSION", INT2NUM(CAPICOM_OID_APPLICATION_POLICY_CONSTRAINTS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_AUTHORITY_INFO_ACCESS_EXTENSION", INT2NUM(CAPICOM_OID_AUTHORITY_INFO_ACCESS_EXTENSION));
  rb_define_const(module,  "CAPICOM_OID_SERVER_AUTH_EKU", INT2NUM(CAPICOM_OID_SERVER_AUTH_EKU));
  rb_define_const(module,  "CAPICOM_OID_CLIENT_AUTH_EKU", INT2NUM(CAPICOM_OID_CLIENT_AUTH_EKU));
  rb_define_const(module,  "CAPICOM_OID_CODE_SIGNING_EKU", INT2NUM(CAPICOM_OID_CODE_SIGNING_EKU));
  rb_define_const(module,  "CAPICOM_OID_EMAIL_PROTECTION_EKU", INT2NUM(CAPICOM_OID_EMAIL_PROTECTION_EKU));
  rb_define_const(module,  "CAPICOM_OID_IPSEC_END_SYSTEM_EKU", INT2NUM(CAPICOM_OID_IPSEC_END_SYSTEM_EKU));
  rb_define_const(module,  "CAPICOM_OID_IPSEC_TUNNEL_EKU", INT2NUM(CAPICOM_OID_IPSEC_TUNNEL_EKU));
  rb_define_const(module,  "CAPICOM_OID_IPSEC_USER_EKU", INT2NUM(CAPICOM_OID_IPSEC_USER_EKU));
  rb_define_const(module,  "CAPICOM_OID_TIME_STAMPING_EKU", INT2NUM(CAPICOM_OID_TIME_STAMPING_EKU));
  rb_define_const(module,  "CAPICOM_OID_CTL_USAGE_SIGNING_EKU", INT2NUM(CAPICOM_OID_CTL_USAGE_SIGNING_EKU));
  rb_define_const(module,  "CAPICOM_OID_TIME_STAMP_SIGNING_EKU", INT2NUM(CAPICOM_OID_TIME_STAMP_SIGNING_EKU));
  rb_define_const(module,  "CAPICOM_OID_SERVER_GATED_CRYPTO_EKU", INT2NUM(CAPICOM_OID_SERVER_GATED_CRYPTO_EKU));
  rb_define_const(module,  "CAPICOM_OID_ENCRYPTING_FILE_SYSTEM_EKU", INT2NUM(CAPICOM_OID_ENCRYPTING_FILE_SYSTEM_EKU));
  rb_define_const(module,  "CAPICOM_OID_EFS_RECOVERY_EKU", INT2NUM(CAPICOM_OID_EFS_RECOVERY_EKU));
  rb_define_const(module,  "CAPICOM_OID_WHQL_CRYPTO_EKU", INT2NUM(CAPICOM_OID_WHQL_CRYPTO_EKU));
  rb_define_const(module,  "CAPICOM_OID_NT5_CRYPTO_EKU", INT2NUM(CAPICOM_OID_NT5_CRYPTO_EKU));
  rb_define_const(module,  "CAPICOM_OID_OEM_WHQL_CRYPTO_EKU", INT2NUM(CAPICOM_OID_OEM_WHQL_CRYPTO_EKU));
  rb_define_const(module,  "CAPICOM_OID_EMBEDED_NT_CRYPTO_EKU", INT2NUM(CAPICOM_OID_EMBEDED_NT_CRYPTO_EKU));
  rb_define_const(module,  "CAPICOM_OID_ROOT_LIST_SIGNER_EKU", INT2NUM(CAPICOM_OID_ROOT_LIST_SIGNER_EKU));
  rb_define_const(module,  "CAPICOM_OID_QUALIFIED_SUBORDINATION_EKU", INT2NUM(CAPICOM_OID_QUALIFIED_SUBORDINATION_EKU));
  rb_define_const(module,  "CAPICOM_OID_KEY_RECOVERY_EKU", INT2NUM(CAPICOM_OID_KEY_RECOVERY_EKU));
  rb_define_const(module,  "CAPICOM_OID_DIGITAL_RIGHTS_EKU", INT2NUM(CAPICOM_OID_DIGITAL_RIGHTS_EKU));
  rb_define_const(module,  "CAPICOM_OID_LICENSES_EKU", INT2NUM(CAPICOM_OID_LICENSES_EKU));
  rb_define_const(module,  "CAPICOM_OID_LICENSE_SERVER_EKU", INT2NUM(CAPICOM_OID_LICENSE_SERVER_EKU));
  rb_define_const(module,  "CAPICOM_OID_SMART_CARD_LOGON_EKU", INT2NUM(CAPICOM_OID_SMART_CARD_LOGON_EKU));
  rb_define_const(module,  "CAPICOM_OID_PKIX_POLICY_QUALIFIER_CPS", INT2NUM(CAPICOM_OID_PKIX_POLICY_QUALIFIER_CPS));
  rb_define_const(module,  "CAPICOM_OID_PKIX_POLICY_QUALIFIER_USERNOTICE", INT2NUM(CAPICOM_OID_PKIX_POLICY_QUALIFIER_USERNOTICE));
  // ...  enum _CAPICOM_PROV_TYPE
  rb_define_const(module,  "CAPICOM_PROV_RSA_FULL", INT2NUM(CAPICOM_PROV_RSA_FULL));
  rb_define_const(module,  "CAPICOM_PROV_RSA_SIG", INT2NUM(CAPICOM_PROV_RSA_SIG));
  rb_define_const(module,  "CAPICOM_PROV_DSS", INT2NUM(CAPICOM_PROV_DSS));
  rb_define_const(module,  "CAPICOM_PROV_FORTEZZA", INT2NUM(CAPICOM_PROV_FORTEZZA));
  rb_define_const(module,  "CAPICOM_PROV_MS_EXCHANGE", INT2NUM(CAPICOM_PROV_MS_EXCHANGE));
  rb_define_const(module,  "CAPICOM_PROV_SSL", INT2NUM(CAPICOM_PROV_SSL));
  rb_define_const(module,  "CAPICOM_PROV_RSA_SCHANNEL", INT2NUM(CAPICOM_PROV_RSA_SCHANNEL));
  rb_define_const(module,  "CAPICOM_PROV_DSS_DH", INT2NUM(CAPICOM_PROV_DSS_DH));
  rb_define_const(module,  "CAPICOM_PROV_EC_ECDSA_SIG", INT2NUM(CAPICOM_PROV_EC_ECDSA_SIG));
  rb_define_const(module,  "CAPICOM_PROV_EC_ECNRA_SIG", INT2NUM(CAPICOM_PROV_EC_ECNRA_SIG));
  rb_define_const(module,  "CAPICOM_PROV_EC_ECDSA_FULL", INT2NUM(CAPICOM_PROV_EC_ECDSA_FULL));
  rb_define_const(module,  "CAPICOM_PROV_EC_ECNRA_FULL", INT2NUM(CAPICOM_PROV_EC_ECNRA_FULL));
  rb_define_const(module,  "CAPICOM_PROV_DH_SCHANNEL", INT2NUM(CAPICOM_PROV_DH_SCHANNEL));
  rb_define_const(module,  "CAPICOM_PROV_SPYRUS_LYNKS", INT2NUM(CAPICOM_PROV_SPYRUS_LYNKS));
  rb_define_const(module,  "CAPICOM_PROV_RNG", INT2NUM(CAPICOM_PROV_RNG));
  rb_define_const(module,  "CAPICOM_PROV_INTEL_SEC", INT2NUM(CAPICOM_PROV_INTEL_SEC));
  rb_define_const(module,  "CAPICOM_PROV_REPLACE_OWF", INT2NUM(CAPICOM_PROV_REPLACE_OWF));
  rb_define_const(module,  "CAPICOM_PROV_RSA_AES", INT2NUM(CAPICOM_PROV_RSA_AES));
  // ...  enum _CAPICOM_KEY_SPEC
  rb_define_const(module,  "CAPICOM_KEY_SPEC_KEYEXCHANGE", INT2NUM(CAPICOM_KEY_SPEC_KEYEXCHANGE));
  rb_define_const(module,  "CAPICOM_KEY_SPEC_SIGNATURE", INT2NUM(CAPICOM_KEY_SPEC_SIGNATURE));
  // ...
  rb_define_const(module,  "CADESCOM_AllowNone", INT2NUM(0x00));
  rb_define_const(module,  "CADESCOM_AllowNoOutstandingRequest", INT2NUM(0x01));
  rb_define_const(module,  "CADESCOM_AllowUntrustedCertificate", INT2NUM(0x02));
  rb_define_const(module,  "CADESCOM_AllowUntrustedRoot", INT2NUM(0x04));
  rb_define_const(module,  "CADESCOM_SkipInstallToStore", INT2NUM(0x10000000));
  rb_define_const(module,  "ENABLE_CARRIER_TYPE_CSP", INT2NUM(0x01));
  rb_define_const(module,  "ENABLE_CARRIER_TYPE_FKC_NO_SM", INT2NUM(0x02));
  rb_define_const(module,  "ENABLE_CARRIER_TYPE_FKC_SM", INT2NUM(0x04));
  rb_define_const(module,  "ENABLE_ANY_CARRIER_TYPE", INT2NUM(0x07));
  rb_define_const(module,  "DISABLE_EVERY_CARRIER_OPERATION", INT2NUM(0x00));
  rb_define_const(module,  "ENABLE_CARRIER_OPEN_ENUM", INT2NUM(0x01));
  rb_define_const(module,  "ENABLE_CARRIER_CREATE", INT2NUM(0x02));
  rb_define_const(module,  "ENABLE_ANY_OPERATION", INT2NUM(0x03));
  rb_define_const(module,  "MEDIA_TYPE_REGISTRY", INT2NUM(0x00000001));
  rb_define_const(module,  "MEDIA_TYPE_HDIMAGE", INT2NUM(0x00000002));
  rb_define_const(module,  "MEDIA_TYPE_CLOUD", INT2NUM(0x00000004));
  rb_define_const(module,  "MEDIA_TYPE_SCARD", INT2NUM(0x00000008));
  rb_define_const(module,  "XCN_CRYPT_STRING_BASE64HEADER", INT2NUM(0));
  rb_define_const(module,  "AT_KEYEXCHANGE", INT2NUM(1));
  rb_define_const(module,  "AT_SIGNATURE", INT2NUM(2));
  rb_define_const(module,  "CADESCOM_ENCODE_ANY", INT2NUM(-1));
  rb_define_const(module,  "CAPICOM_EKU_ENCRYPTING_FILE_SYSTEM", INT2NUM(6));
  rb_define_const(module,  "CAPICOM_PROPID_KEY_PROV_INFO", INT2NUM(2));
  rb_define_const(module,  "CAPICOM_DATA_ENCIPHERMENT_KEY_USAGE", INT2NUM(16));
  rb_define_const(module,  "CAPICOM_DIGITAL_SIGNATURE_KEY_USAGE", INT2NUM(128));
  rb_define_const(module,  "CAPICOM_MY_STORE", rb_str_new2("My"));
  rb_define_const(module,  "CAPICOM_CA_STORE", rb_str_new2("CA"));
  rb_define_const(module,  "CAPICOM_ROOT_STORE", rb_str_new2("Root"));
  rb_define_const(module,  "CAPICOM_OTHER_STORE", rb_str_new2("AddressBook"));
  rb_define_const(module,  "XmlDsigGost3410UrlObsolete", rb_str_new2("http://www.w3.org/2001/04/xmldsig-more#gostr34102001-gostr3411"));
  rb_define_const(module,  "XmlDsigGost3411UrlObsolete", rb_str_new2("http://www.w3.org/2001/04/xmldsig-more#gostr3411"));
  rb_define_const(module,  "XmlDsigGost3410Url", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102001-gostr3411"));
  rb_define_const(module,  "XmlDsigGost3411Url", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr3411"));
  rb_define_const(module,  "XmlDsigGost3410Url2012256", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-256"));
  rb_define_const(module,  "XmlDsigGost3411Url2012256", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34112012-256"));
  rb_define_const(module,  "XmlDsigGost3410Url2012512", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-512"));
  rb_define_const(module,  "XmlDsigGost3411Url2012512", rb_str_new2("urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34112012-512"));
}
}
